apiVersion: v1
kind: Service
metadata:
  name: fiap-video-request-api
  namespace: default
  labels:
    app: fiap-video-request-api
    context: video-slicer
spec:
  selector:
    app: fiap-video-request-api
  ports:  
  - name: api
    protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer